services:
  django:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: ["python", "manage.py", "runserver","0.0.0.0:8000"]
  frontend:
    build:
      context: ./frontend/DMS-Frontend
    working_dir: /DMS-Frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/DMS-Frontend/public:/DMS-Frontend/public
      - ./frontend/DMS-Frontend/src:/DMS-Frontend/src
    command:  ["npm","run","dev"]
