/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAttribute: typeof import('./src/components/AddAttribute.vue')['default']
    AttributesValueInput: typeof import('./src/components/AttributesValueInput.vue')['default']
    AttributesWithPdf: typeof import('./src/components/AttributesWithPdf.vue')['default']
    AttributteValueInput: typeof import('./src/components/AttributteValueInput.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    CreateArchive: typeof import('./src/components/CreateArchive.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ListArchives: typeof import('./src/components/ListArchives.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    PdfViewer: typeof import('./src/components/PdfViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Toast: typeof import('primevue/toast')['default']
    UploadPDF: typeof import('./src/components/uploadPDF.vue')['default']
  }
}
