/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ListArchives: typeof import('./src/components/listArchives.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    PdfViewer: typeof import('./src/components/PdfViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('primevue/toast')['default']
    UploadPDF: typeof import('./src/components/uploadPDF.vue')['default']
  }
}
